require("qberg.options")
require("qberg.keymaps")
require("qberg.plugins")
require("qberg.colorscheme")
require("qberg.cmp")
require("qberg.telescope")
require("qberg.treesitter")
require("qberg.lsp")
