require("qberg.plugins-setup")
require("qberg.core.options")
require("qberg.core.keymaps")
require("qberg.core.colorscheme")
require("qberg.plugins.nvim-tree")
require("qberg.plugins.lualine")
require("qberg.plugins.telescope")
require("qberg.plugins.nvim-cmp")
require("qberg.plugins.lsp.mason")
-- require("qberg.plugins.treesitter") deprecated for the timebeing
require("qberg.plugins.autopairs")
