require("qberg.plugins-setup")
require("qberg.core.options")
require("qberg.core.keymaps")
require("qberg.core.colorscheme")
require("qberg.plugins.nvim-tree")
require("qberg.plugins.lualine")
-- require("qberg.options")
-- require("qberg.keymaps")
-- require("qberg.plugins")
-- require("qberg.colorscheme")
-- require("qberg.cmp")
-- require("qberg.telescope")
-- require("qberg.treesitter")
--  require("qberg.lsp")
